class CodeGenerator {
    static generateCodeFromBlocks(workspace) {
        if (!workspace) return '// Blockly не инициализирован';

        try {
            // Инициализация парсера
            const parser = new BlockParser(workspace);
            const { setupCode, loopCode, globalVars, usedBlockTypes } = parser.parseWorkspace();

            // Получение библиотек
            const libraryManager = new LibraryManager();
            const { includes, declarations } = libraryManager.getRequiredLibraries(usedBlockTypes, workspace);

            // Генерация хелперов
            const helperGenerator = new HelperGenerator();
            const helpers = helperGenerator.generateHelpers(usedBlockTypes);

            // Генерация инициализации
            const initializationGenerator = new InitializationGenerator();
            const initCode = initializationGenerator.generateInitialization(usedBlockTypes, workspace);

            // Удаление дубликатов
         /*   const uniqueGlobalVars = this.removeDuplicates(globalVars);
            const uniqueSetupCode = this.removeDuplicates(setupCode);
            const uniqueLoopCode = this.removeDuplicates(loopCode);
            const uniqueInitCode = this.removeDuplicates(initCode);*/

            return this.generateCompleteCode(
                includes,
                declarations,
                globalVars,
                helpers,
                setupCode,
                loopCode,
                initCode
            );
        } catch (error) {
            console.error('Error generating code:', error);
            return `// Ошибка генерации кода: ${error.message}`;
        }
    }

    static removeDuplicates(array) {
        const seen = new Set();
        const result = [];

        array.forEach(item => {
            const normalized = item.trim().replace(/\s+/g, ' ');
            if (!seen.has(normalized)) {
                seen.add(normalized);
                result.push(item);
            }
        });

        return result;
    }

    static generateCompleteCode(includes, declarations, globalVars, helpers, setupCode, loopCode, initCode) {
        let arduinoCode = `// Generated by КонтрБагКОД
// ${new Date().toLocaleString()}

`;

        // Include statements
        if (includes.size > 0) {
            arduinoCode += Array.from(includes).join('\n') + '\n\n';
        }

        // Global declarations
        if (declarations.size > 0) {
            arduinoCode += Array.from(declarations).join('\n') + '\n\n';
        }

        // Глобальные переменные
        if (globalVars.length > 0) {
            arduinoCode += globalVars.join('\n') + '\n\n';
        }

        // Вспомогательные функции
        if (helpers && helpers.trim()) {
            arduinoCode += helpers + '\n';
        }

        // Функция setup
        const setupContent = [];
        if (setupCode.length > 0) {
            setupContent.push(...setupCode.map(line => `  ${line}`));
        }
        if (initCode.length > 0) {
            setupContent.push(...initCode.map(line => `  ${line}`));
        }

        if (setupContent.length > 0) {
            arduinoCode += `void setup() {\n${setupContent.join('\n')}\n}\n\n`;
        } else {
            arduinoCode += `void setup() {\n  // Настройки\n}\n\n`;
        }

        // Функция loop
        if (loopCode.length > 0) {
            arduinoCode += `void loop() {\n${loopCode.map(line => `  ${line}`).join('\n')}\n}`;
        } else {
            arduinoCode += `void loop() {\n  // Основной цикл\n}`;
        }

        return arduinoCode;
    }
}